import { defineConfig, type Options } from 'tsup';

const entry = {
  'accordion/blessed': 'src/adapters/blessed/accordion.ts',
  'accordion/index': 'src/components/layout/accordion/index.ts',
  'app-shell/blessed': 'src/adapters/blessed/app-shell.ts',
  'app-shell/index': 'src/components/layout/app-shell/index.ts',
  'alert/blessed': 'src/adapters/blessed/alert.ts',
  'alert/index': 'src/components/feedback/alert/index.ts',
  'badge/blessed': 'src/adapters/blessed/badge.ts',
  'badge/index': 'src/components/data-display/badge/index.ts',
  'breadcrumb/blessed': 'src/adapters/blessed/breadcrumb.ts',
  'breadcrumb/index': 'src/components/data-display/breadcrumb/index.ts',
  'box/blessed': 'src/adapters/blessed/box.ts',
  'box/index': 'src/components/layout/box/index.ts',
  'button/blessed': 'src/adapters/blessed/button.ts',
  'button/index': 'src/components/input/button/index.ts',
  'card/blessed': 'src/adapters/blessed/card.ts',
  'card/index': 'src/components/layout/card/index.ts',
  'center/blessed': 'src/adapters/blessed/center.ts',
  'center/index': 'src/components/layout/center/index.ts',
  'cluster/blessed': 'src/adapters/blessed/cluster.ts',
  'cluster/index': 'src/components/layout/cluster/index.ts',
  'collapsible/blessed': 'src/adapters/blessed/collapsible.ts',
  'collapsible/index': 'src/components/layout/collapsible/index.ts',
  'callout/blessed': 'src/adapters/blessed/callout.ts',
  'callout/index': 'src/components/feedback/callout/index.ts',
  'checkbox/blessed': 'src/adapters/blessed/checkbox.ts',
  'checkbox/index': 'src/components/input/checkbox/index.ts',
  'code/blessed': 'src/adapters/blessed/code.ts',
  'code/index': 'src/components/data-display/code/index.ts',
  'confirm-dialog/blessed': 'src/adapters/blessed/confirm-dialog.ts',
  'confirm-dialog/index': 'src/components/overlays/confirm-dialog/index.ts',
  'connection-status/blessed': 'src/adapters/blessed/connection-status.ts',
  'connection-status/index': 'src/components/feedback/connection-status/index.ts',
  'description-list/blessed': 'src/adapters/blessed/description-list.ts',
  'description-list/index': 'src/components/data-display/description-list/index.ts',
  'core/capabilities': 'src/core/capabilities.ts',
  'core/characters': 'src/core/characters.ts',
  'core/color': 'src/core/color.ts',
  'core/crop': 'src/core/crop.ts',
  'core/events': 'src/core/events.ts',
  'core/focus': 'src/core/focus.ts',
  'core/format': 'src/core/format.ts',
  'core/index': 'src/core/index.ts',
  'core/keymap': 'src/core/keymap.ts',
  'core/layout': 'src/core/layout.ts',
  'core/render-model': 'src/core/render-model.ts',
  'core/scale': 'src/core/scale.ts',
  'core/tags': 'src/core/tags.ts',
  'core/theme': 'src/core/theme.ts',
  'core/truncate': 'src/core/truncate.ts',
  'core/width': 'src/core/width.ts',
  'divider/blessed': 'src/adapters/blessed/divider.ts',
  'divider/index': 'src/components/layout/divider/index.ts',
  'dialog/blessed': 'src/adapters/blessed/dialog.ts',
  'dialog/index': 'src/components/overlays/dialog/index.ts',
  'empty-state/blessed': 'src/adapters/blessed/empty-state.ts',
  'empty-state/index': 'src/components/feedback/empty-state/index.ts',
  'error-state/blessed': 'src/adapters/blessed/error-state.ts',
  'error-state/index': 'src/components/feedback/error-state/index.ts',
  'form/blessed': 'src/adapters/blessed/form.ts',
  'form/index': 'src/components/input/form/index.ts',
  'form-field/blessed': 'src/adapters/blessed/form-field.ts',
  'form-field/index': 'src/components/input/form-field/index.ts',
  'gauge/blessed': 'src/adapters/blessed/gauge.ts',
  'gauge/index': 'src/components/visualization/gauge/index.ts',
  'grid/blessed': 'src/adapters/blessed/grid.ts',
  'grid/index': 'src/components/layout/grid/index.ts',
  'grouped-list/blessed': 'src/adapters/blessed/grouped-list.ts',
  'grouped-list/index': 'src/components/collections/grouped-list/index.ts',
  'heading/blessed': 'src/adapters/blessed/heading.ts',
  'heading/index': 'src/components/data-display/heading/index.ts',
  'health-indicator/blessed': 'src/adapters/blessed/health-indicator.ts',
  'health-indicator/index': 'src/components/feedback/health-indicator/index.ts',
  'help-overlay/blessed': 'src/adapters/blessed/help-overlay.ts',
  'help-overlay/index': 'src/components/navigation/help-overlay/index.ts',
  index: 'src/index.ts',
  'kbd/blessed': 'src/adapters/blessed/kbd.ts',
  'kbd/index': 'src/components/data-display/kbd/index.ts',
  'key-value/blessed': 'src/adapters/blessed/key-value.ts',
  'key-value/index': 'src/components/data-display/key-value/index.ts',
  'label/blessed': 'src/adapters/blessed/label.ts',
  'label/index': 'src/components/data-display/label/index.ts',
  'legend/blessed': 'src/adapters/blessed/legend.ts',
  'legend/index': 'src/components/visualization/legend/index.ts',
  'list/blessed': 'src/adapters/blessed/list.ts',
  'list/index': 'src/components/collections/list/index.ts',
  'log-viewer/blessed': 'src/adapters/blessed/log-viewer.ts',
  'log-viewer/index': 'src/components/collections/log-viewer/index.ts',
  'loading-overlay/blessed': 'src/adapters/blessed/loading-overlay.ts',
  'loading-overlay/index': 'src/components/feedback/loading-overlay/index.ts',
  'menu/blessed': 'src/adapters/blessed/menu.ts',
  'menu/index': 'src/components/navigation/menu/index.ts',
  'metric-bars/blessed': 'src/adapters/blessed/metric-bars.ts',
  'metric-bars/index': 'src/components/visualization/metric-bars/index.ts',
  'multi-select/blessed': 'src/adapters/blessed/multi-select.ts',
  'multi-select/index': 'src/components/input/multi-select/index.ts',
  'muted-text/blessed': 'src/adapters/blessed/muted-text.ts',
  'muted-text/index': 'src/components/data-display/muted-text/index.ts',
  'multi-sparkline/blessed': 'src/adapters/blessed/multi-sparkline.ts',
  'multi-sparkline/index': 'src/components/visualization/multi-sparkline/index.ts',
  'overlay/blessed': 'src/adapters/blessed/overlay.ts',
  'overlay/index': 'src/components/overlays/overlay/index.ts',
  'page/blessed': 'src/adapters/blessed/page.ts',
  'page/index': 'src/components/layout/page/index.ts',
  'preformatted/blessed': 'src/adapters/blessed/preformatted.ts',
  'preformatted/index': 'src/components/data-display/preformatted/index.ts',
  'progress-bar/blessed': 'src/adapters/blessed/progress-bar.ts',
  'progress-bar/index': 'src/components/feedback/progress-bar/index.ts',
  'progress-list/blessed': 'src/adapters/blessed/progress-list.ts',
  'progress-list/index': 'src/components/feedback/progress-list/index.ts',
  'progress-stack/blessed': 'src/adapters/blessed/progress-stack.ts',
  'progress-stack/index': 'src/components/feedback/progress-stack/index.ts',
  'radio-group/blessed': 'src/adapters/blessed/radio-group.ts',
  'radio-group/index': 'src/components/input/radio-group/index.ts',
  'search-field/blessed': 'src/adapters/blessed/search-field.ts',
  'search-field/index': 'src/components/input/search-field/index.ts',
  'select/blessed': 'src/adapters/blessed/select.ts',
  'select/index': 'src/components/input/select/index.ts',
  'scroll-area/blessed': 'src/adapters/blessed/scroll-area.ts',
  'scroll-area/index': 'src/components/layout/scroll-area/index.ts',
  'sidebar-layout/blessed': 'src/adapters/blessed/sidebar-layout.ts',
  'sidebar-layout/index': 'src/components/layout/sidebar-layout/index.ts',
  'spacer/blessed': 'src/adapters/blessed/spacer.ts',
  'spacer/index': 'src/components/layout/spacer/index.ts',
  'primitives/collection/index': 'src/primitives/collection/index.ts',
  'primitives/focus-scope/index': 'src/primitives/focus-scope/index.ts',
  'primitives/index': 'src/primitives/index.ts',
  'primitives/overlay/index': 'src/primitives/overlay/index.ts',
  'primitives/scroll-area/index': 'src/primitives/scroll-area/index.ts',
  'primitives/selection/index': 'src/primitives/selection/index.ts',
  'primitives/viewport/index': 'src/primitives/viewport/index.ts',
  'sparkline/blessed': 'src/adapters/blessed/sparkline.ts',
  'sparkline/index': 'src/components/visualization/sparkline/index.ts',
  'spinner/blessed': 'src/adapters/blessed/spinner.ts',
  'spinner/index': 'src/components/feedback/spinner/index.ts',
  'status/blessed': 'src/adapters/blessed/status.ts',
  'status/index': 'src/components/feedback/status/index.ts',
  'step-indicator/blessed': 'src/adapters/blessed/step-indicator.ts',
  'step-indicator/index': 'src/components/feedback/step-indicator/index.ts',
  'switch/blessed': 'src/adapters/blessed/switch.ts',
  'switch/index': 'src/components/input/switch/index.ts',
  'tab-list/blessed': 'src/adapters/blessed/tab-list.ts',
  'tab-list/index': 'src/components/navigation/tab-list/index.ts',
  'task-progress/blessed': 'src/adapters/blessed/task-progress.ts',
  'task-progress/index': 'src/components/feedback/task-progress/index.ts',
  'toast/blessed': 'src/adapters/blessed/toast.ts',
  'toast/index': 'src/components/feedback/toast/index.ts',
  'tabs/blessed': 'src/adapters/blessed/tabs.ts',
  'tabs/index': 'src/components/navigation/tabs/index.ts',
  'table/blessed': 'src/adapters/blessed/table.ts',
  'table/index': 'src/components/collections/table/index.ts',
  'data-table/blessed': 'src/adapters/blessed/data-table.ts',
  'data-table/index': 'src/components/collections/data-table/index.ts',
  'timeline/blessed': 'src/adapters/blessed/timeline.ts',
  'timeline/index': 'src/components/collections/timeline/index.ts',
  'virtual-list/blessed': 'src/adapters/blessed/virtual-list.ts',
  'virtual-list/index': 'src/components/collections/virtual-list/index.ts',
  'stack/blessed': 'src/adapters/blessed/stack.ts',
  'stack/index': 'src/components/layout/stack/index.ts',
  'stacked-gauge/blessed': 'src/adapters/blessed/stacked-gauge.ts',
  'stacked-gauge/index': 'src/components/visualization/stacked-gauge/index.ts',
  'stat/blessed': 'src/adapters/blessed/stat.ts',
  'stat/index': 'src/components/data-display/stat/index.ts',
  'tag/blessed': 'src/adapters/blessed/tag.ts',
  'tag/index': 'src/components/data-display/tag/index.ts',
  'text/blessed': 'src/adapters/blessed/text.ts',
  'text/index': 'src/components/data-display/text/index.ts',
  'text-field/blessed': 'src/adapters/blessed/text-field.ts',
  'text-field/index': 'src/components/input/text-field/index.ts',
  'timestamp/blessed': 'src/adapters/blessed/timestamp.ts',
  'timestamp/index': 'src/components/data-display/timestamp/index.ts',
  'thresholds/blessed': 'src/adapters/blessed/thresholds.ts',
  'thresholds/index': 'src/components/visualization/thresholds/index.ts',
  'trend/blessed': 'src/adapters/blessed/trend.ts',
  'trend/index': 'src/components/data-display/trend/index.ts',
  'viewport/blessed': 'src/adapters/blessed/viewport.ts',
  'viewport/index': 'src/components/layout/viewport/index.ts',
};
const entryChunks = Array.from(
  { length: Math.ceil(Object.entries(entry).length / 35) },
  (_, index) => Object.fromEntries(Object.entries(entry).slice(index * 35, (index + 1) * 35)),
);
const sharedConfig: Omit<Options, 'clean' | 'entry'> = {
  dts: true,
  format: ['esm', 'cjs'],
  outExtension({ format }) {
    return {
      js: format === 'cjs' ? '.cjs' : '.js',
    };
  },
  platform: 'node',
  sourcemap: true,
  splitting: false,
  target: 'node22',
  treeshake: true,
} as const;

export default entryChunks.map((chunk, index) =>
  defineConfig({
    ...sharedConfig,
    clean: index === 0,
    entry: chunk,
  }),
);
