import { defineConfig } from 'tsup';

export default defineConfig({
  clean: true,
  dts: true,
  entry: {
    'badge/blessed': 'src/adapters/blessed/badge.ts',
    'badge/index': 'src/components/data-display/badge/index.ts',
    'box/blessed': 'src/adapters/blessed/box.ts',
    'box/index': 'src/components/layout/box/index.ts',
    'card/blessed': 'src/adapters/blessed/card.ts',
    'card/index': 'src/components/layout/card/index.ts',
    'core/capabilities': 'src/core/capabilities.ts',
    'core/characters': 'src/core/characters.ts',
    'core/color': 'src/core/color.ts',
    'core/crop': 'src/core/crop.ts',
    'core/events': 'src/core/events.ts',
    'core/focus': 'src/core/focus.ts',
    'core/format': 'src/core/format.ts',
    'core/index': 'src/core/index.ts',
    'core/keymap': 'src/core/keymap.ts',
    'core/layout': 'src/core/layout.ts',
    'core/render-model': 'src/core/render-model.ts',
    'core/scale': 'src/core/scale.ts',
    'core/tags': 'src/core/tags.ts',
    'core/theme': 'src/core/theme.ts',
    'core/truncate': 'src/core/truncate.ts',
    'core/width': 'src/core/width.ts',
    'divider/blessed': 'src/adapters/blessed/divider.ts',
    'divider/index': 'src/components/layout/divider/index.ts',
    'dialog/blessed': 'src/adapters/blessed/dialog.ts',
    'dialog/index': 'src/components/overlays/dialog/index.ts',
    index: 'src/index.ts',
    'list/blessed': 'src/adapters/blessed/list.ts',
    'list/index': 'src/components/collections/list/index.ts',
    'metric-bars/blessed': 'src/adapters/blessed/metric-bars.ts',
    'metric-bars/index': 'src/components/visualization/metric-bars/index.ts',
    'progress-bar/blessed': 'src/adapters/blessed/progress-bar.ts',
    'progress-bar/index': 'src/components/feedback/progress-bar/index.ts',
    'primitives/collection/index': 'src/primitives/collection/index.ts',
    'primitives/focus-scope/index': 'src/primitives/focus-scope/index.ts',
    'primitives/index': 'src/primitives/index.ts',
    'primitives/overlay/index': 'src/primitives/overlay/index.ts',
    'primitives/scroll-area/index': 'src/primitives/scroll-area/index.ts',
    'primitives/selection/index': 'src/primitives/selection/index.ts',
    'primitives/viewport/index': 'src/primitives/viewport/index.ts',
    'sparkline/blessed': 'src/adapters/blessed/sparkline.ts',
    'sparkline/index': 'src/components/visualization/sparkline/index.ts',
    'spinner/blessed': 'src/adapters/blessed/spinner.ts',
    'spinner/index': 'src/components/feedback/spinner/index.ts',
    'stack/blessed': 'src/adapters/blessed/stack.ts',
    'stack/index': 'src/components/layout/stack/index.ts',
    'stat/blessed': 'src/adapters/blessed/stat.ts',
    'stat/index': 'src/components/data-display/stat/index.ts',
    'text/blessed': 'src/adapters/blessed/text.ts',
    'text/index': 'src/components/data-display/text/index.ts',
  },
  format: ['esm', 'cjs'],
  outExtension({ format }) {
    return {
      js: format === 'cjs' ? '.cjs' : '.js',
    };
  },
  platform: 'node',
  sourcemap: true,
  splitting: false,
  target: 'node22',
  treeshake: true,
});
